### ISSUE TITLE
THREE.WebGLRenderer: Context Lost.

### ISSUE THREAD

**Issue by ndimatteo** [JohnnyLeek1/React-Mesh-Gradient#2]
Hey there @JohnnyLeek1! First of all, awesome job with this, the gradient animations are killer! 🤘 

Everything is working perfectly, but I did notice the following `console.log()` pop-up repeatedly when changing routes within Next.js:
```
THREE.WebGLRenderer: Context Lost.
```

It doesn't seem to be causing any notable perf issues, but I'm curious what your thoughts are.

**Comment by JohnnyLeek1** [comment]
Hi there! Thank you for the kind words :) 

Give me some time to look into this, I'm imagining I'm not unmounting the canvas correctly / at all. 

I'll set up a sandbox later tonight and take a look

**Comment by lhnfe** [comment]
Hey @JohnnyLeek1, i have the same problem. Do you have the solution to resolve this problem, because i have a perf issues on my website (WARNING: Too many active WebGL contexts. Oldest context will be lost.).

**Comment by kylegillen** [comment]
Any luck?

**Comment by JohnnyLeek1** [comment]
Hi @ndimatteo @Sybrax @kylegillen , I completely forgot about this repository, but I see that it has gained some traction and am actively maintaining it again. This issue is now fixed in version 1.1.1.

Thanks!
